%%%CreateAE(points, Layers, Epochs, NumOfLayer)
function ae = CreateAE(points, Layers, Epochs, NumOfLayer)
    if NumOfLayer == 1
        ae = trainAutoencoder(points, Layers(1),...
                                'MaxEpochs', Epochs,...
                                'L2WeightRegularization', 0.001, ...
                                'SparsityRegularization', 4, ...
                                'SparsityProportion', 0.05, ...
                                'DecoderTransferFunction','purelin');
    else
        aes = [];
        out = points;
        for i = 1:NumOfLayer
            aes = [aes;trainAutoencoder(out, Layers(i),...
                                'MaxEpochs', Epochs,...
                                'L2WeightRegularization', 0.001, ...
                                'SparsityRegularization', 4, ...
                                'SparsityProportion', 0.05, ...
                                'DecoderTransferFunction','purelin')];
            tmpAE = aes(i);
            out = encode(tmpAE,out);
        end
        if NumOfLayer == 2
        ae = stack(aes(1),aes(2));
        else 
            if NumOfLayer == 3
                ae = stack(aes(1), aes(2), aes(3));
            end
        end
        ae = train(ae, points);
    end
end