function sum = sumofneibors(an,h,v)
    a = an;
    filter = [...
            [0.5 0.5 0.5];...
            [0.5 4 0.5];...
            [0.5 0.5 0.5];...
        ];
    a(a<1) = 0;
    t = conv2(a,filter,'same')/4;
    t(t<=1) = 0;
    sum = fix(t(h,v));
end